from datetime import date
from src.books.schema import Book

books = [
    Book(
        id=1,
        title="To Kill a Mockingbird",
        author="Harper Lee",
        publisher="J.B. Lippincott & Co.",
        published_date=date(1960, 7, 11),
        page_count=281,
        language="en",
    ),
    Book(
        id=2,
        title="1984",
        author="George Orwell",
        publisher="Secker & Warburg",
        published_date=date(1949, 6, 8),
        page_count=328,
        language="en",
    ),
    Book(
        id=3,
        title="One Hundred Years of Solitude",
        author="Gabriel García Márquez",
        publisher="Harper & Row",
        published_date=date(1970, 6, 5),
        page_count=417,
        language="en",
    ),
    Book(
        id=4,
        title="The Catcher in the Rye",
        author="J.D. Salinger",
        publisher="Little, Brown and Company",
        published_date=date(1951, 7, 16),
        page_count=277,
        language="en",
    ),
    Book(
        id=5,
        title="Pride and Prejudice",
        author="Jane Austen",
        publisher="T. Egerton",
        published_date=date(1813, 1, 28),
        page_count=279,
        language="en",
    ),
    Book(
        id=6,
        title="The Hobbit",
        author="J.R.R. Tolkien",
        publisher="George Allen & Unwin",
        published_date=date(1937, 9, 21),
        page_count=310,
        language="en",
    ),
    Book(
        id=7,
        title="The Alchemist",
        author="Paulo Coelho",
        publisher="HarperTorch",
        published_date=date(1993, 5, 1),
        page_count=208,
        language="en",
    ),
    Book(
        id=8,
        title="Crime and Punishment",
        author="Fyodor Dostoevsky",
        publisher="The Russian Messenger",
        published_date=date(1866, 1, 1),
        page_count=430,
        language="en",
    ),
    Book(
        id=9,
        title="The Book Thief",
        author="Markus Zusak",
        publisher="Picador",
        published_date=date(2005, 3, 14),
        page_count=552,
        language="en",
    ),
    Book(
        id=10,
        title="Brave New World",
        author="Aldous Huxley",
        publisher="Chatto & Windus",
        published_date=date(1932, 8, 18),
        page_count=311,
        language="en",
    ),
]
